# Site settings
title:              Joseph Blom Portfolio
email:              jblom5400@gmail.com
description:        "Project portfolio for Joseph Blom"
url:                "jrblom2.github.io"
baseurl:            /jrblom2.github.io/

# File structure settings
image_path:         /public/images

# Build settings
markdown:           kramdown
permalink:          pretty

# Collection definitions and settings
collections:
  projects:
    output: true
    permalink: /projects/:path/
