# User config
author: "Joseph Blom"
tagline: "Joseph Blom Portfolio"
description: "Professional portfolio for Joseph Blom"
email: "jblom5400@gmail.com"
linkedin: "//www.linkedin.com/in/joseph-blom-975366231"

# Site config
url:                "http://localhost:4000"
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed